using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using DeadManZone.Core.Tags;
using UnityEditor;
using UnityEngine;

namespace DeadManZone.Data.Editor
{
    internal static class TagCreatorPersistence
    {
        private const string JsonRelativePath = "Assets/_Project/Data/Editor/TagCreator/custom_tags.json";
        private const string GeneratedRelativePath = "Assets/_Project/Core/Tags/CustomTagCatalog.Generated.cs";

        public static string JsonAssetPath => JsonRelativePath;
        public static string GeneratedAssetPath => GeneratedRelativePath;

        public static List<CustomTagRecord> Load()
        {
            string absolutePath = GetAbsolutePath(JsonRelativePath);
            if (!File.Exists(absolutePath))
                return new List<CustomTagRecord>();

            string json = File.ReadAllText(absolutePath);
            if (string.IsNullOrWhiteSpace(json))
                return new List<CustomTagRecord>();

            var wrapper = JsonUtility.FromJson<CustomTagRecordList>(WrapJson(json));
            if (wrapper?.Items == null || wrapper.Items.Length == 0)
                return new List<CustomTagRecord>();

            return new List<CustomTagRecord>(wrapper.Items);
        }

        public static bool TrySave(IReadOnlyList<CustomTagRecord> tags, out string error)
        {
            error = null;
            if (tags == null)
            {
                error = "Tag list is null.";
                return false;
            }

            for (int i = 0; i < tags.Count; i++)
            {
                if (!CustomTagValidator.TryValidate(tags[i], tags, out error))
                    return false;
            }

            WriteJson(tags);
            WriteGeneratedSource(tags);
            AssetDatabase.Refresh();
            return true;
        }

        private static void WriteJson(IReadOnlyList<CustomTagRecord> tags)
        {
            var wrapper = new CustomTagRecordList { Items = ToArray(tags) };
            string json = JsonUtility.ToJson(wrapper, prettyPrint: true);
            string absolutePath = GetAbsolutePath(JsonRelativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath) ?? string.Empty);
            File.WriteAllText(absolutePath, json, Encoding.UTF8);
        }

        private static void WriteGeneratedSource(IReadOnlyList<CustomTagRecord> tags)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated by Tag Creator — do not edit manually>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace DeadManZone.Core.Tags");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class CustomTagCatalog");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IReadOnlyList<KeywordTagEntry> GeneratedEntries { get; } = new KeywordTagEntry[]");
            sb.AppendLine("        {");

            for (int i = 0; i < tags.Count; i++)
            {
                var tag = tags[i];
                sb.AppendLine("            new KeywordTagEntry");
                sb.AppendLine("            {");
                sb.AppendLine($"                Id = \"{Escape(tag.Id)}\",");
                sb.AppendLine($"                DisplayName = \"{Escape(tag.DisplayName)}\",");
                sb.AppendLine($"                Category = TagCategory.{tag.Category},");
                sb.AppendLine($"                Tooltip = \"{Escape(tag.Tooltip)}\",");
                sb.AppendLine($"                DisplayPriority = {tag.DisplayPriority}");
                sb.Append("            }");
                sb.AppendLine(i < tags.Count - 1 ? "," : string.Empty);
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string absolutePath = GetAbsolutePath(GeneratedRelativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(absolutePath) ?? string.Empty);
            File.WriteAllText(absolutePath, sb.ToString(), Encoding.UTF8);
        }

        private static CustomTagRecord[] ToArray(IReadOnlyList<CustomTagRecord> tags)
        {
            var copy = new CustomTagRecord[tags.Count];
            for (int i = 0; i < tags.Count; i++)
                copy[i] = tags[i];
            return copy;
        }

        private static string Escape(string value) =>
            (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static string GetAbsolutePath(string assetPath)
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath) ?? string.Empty;
            return Path.Combine(projectRoot, assetPath.Replace('/', Path.DirectorySeparatorChar));
        }

        /// <summary>JsonUtility requires an object root; wrap bare arrays saved as {"Items":[...]}.</summary>
        private static string WrapJson(string json)
        {
            string trimmed = json.TrimStart();
            if (trimmed.StartsWith("["))
                return "{\"Items\":" + json + "}";
            return json;
        }

        [Serializable]
        private sealed class CustomTagRecordList
        {
            public CustomTagRecord[] Items = Array.Empty<CustomTagRecord>();
        }
    }
}
