using System.Linq;
using DeadManZone.Data;
using DeadManZone.Data.Editor;
using DeadManZone.Game;
using DeadManZone.Presentation.MainMenu;
using DeadManZone.Presentation.Visual;
using TMPro;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;

namespace DeadManZone.Presentation.Editor
{
    public static class MenuSceneSetup
    {
        internal const string ScenesFolder = "Assets/_Project/Scenes";
        internal const string MainMenuPath = ScenesFolder + "/MainMenu.unity";
        private const string RunPath = ScenesFolder + "/Run.unity";

        [MenuItem(DeadManZoneEditorMenus.Run + "Set Play Mode Start Scene to MainMenu")]
        public static void SetPlayModeStartScene()
        {
            var mainMenu = AssetDatabase.LoadAssetAtPath<SceneAsset>(MainMenuPath);
            if (mainMenu == null)
            {
                Debug.LogWarning("MainMenu scene not found. Run DeadManZone/Run/Setup Main Menu & Run Scenes first.");
                return;
            }

            EditorSceneManager.OpenScene(MainMenuPath);
            Debug.Log("Opened MainMenu as the active scene. Press Play to start from the main menu.");
        }

        /// <summary>
        /// MainMenu-only. Run.unity is hand-authored scene state (the ShopV2 build surface)
        /// and is never regenerated by tooling — see RunUiAuthoringLock and the CLAUDE.md
        /// "Run-scene UI is hand-authored" gotcha. This menu used to also rebuild Run.unity
        /// via RunSceneSetup, which stomped the ShopV2 flip (34 ShopV2 refs -> 0) and required
        /// a git restore. That path (RunSceneSetup.cs, "Refresh Run Scene") has been removed.
        /// </summary>
        [MenuItem(DeadManZoneEditorMenus.Run + "Setup Main Menu & Run Scenes")]
        public static void SetupScenes()
        {
            if (AssetDatabase.IsValidFolder(GrittyPostApocalypticUiKitSetup.KitRoot))
                GrittyPostApocalypticUiKitSetup.EnsureTheme();
            else
                UiThemeEditor.EnsureThemeAsset();
            MenuThemeEditor.EnsureMenuTheme();
            FactionCrestAssigner.Assign();
            EnsureFolder(ScenesFolder);
            CreateMainMenuScene();
            UpdateBuildSettings();
            AssetDatabase.SaveAssets();
            Debug.Log("DeadManZone: MainMenu scene created/refreshed. Run.unity is hand-authored and was not touched.");
        }

        [MenuItem(DeadManZoneEditorMenus.Run + "Refresh Main Menu Scene")]
        public static void RefreshMainMenuScene()
        {
            UiThemeEditor.EnsureThemeAsset();
            MenuThemeEditor.EnsureMenuTheme();
            FactionCrestAssigner.Assign();
            EnsureFolder(ScenesFolder);
            CreateMainMenuScene();
            AssetDatabase.SaveAssets();
            Debug.Log("DeadManZone: cinematic MainMenu scene refreshed.");
        }

        [MenuItem(DeadManZoneEditorMenus.Run + "Add Main Menu Warehouse Backdrop")]
        public static void AddMainMenuWarehouseBackdrop()
        {
            if (!MainMenuBackdropBuilder.IsKitAvailable())
            {
                Debug.LogWarning(
                    $"Military Warehouse kit not found at {MainMenuBackdropBuilder.KitRoot}. Import the Synty pack first.");
                return;
            }

            var existing = GameObject.Find(MainMenuBackdropBuilder.RootName);
            if (existing != null)
            {
                Debug.Log($"{MainMenuBackdropBuilder.RootName} already exists in the open scene.");
                return;
            }

            var backdrop = MainMenuBackdropBuilder.TryBuild();
            if (backdrop == null)
                return;

            Undo.RegisterCreatedObjectUndo(backdrop, "Add Main Menu Warehouse Backdrop");
            Debug.Log($"DeadManZone: {MainMenuBackdropBuilder.RootName} added to the open scene.");
        }

        /// <summary>Invoked from Unity batch mode to regenerate MainMenu without touching Run scene.</summary>
        public static void BatchRefreshMainMenuScene()
        {
            RefreshMainMenuScene();
            EditorApplication.Exit(0);
        }

        private static void CreateMainMenuScene()
        {
            CinematicMenuSceneBuilder.BuildAndSave(MainMenuPath);
        }

        internal static RunManager CreateRunManager()
        {
            var go = new GameObject("RunManager");
            var manager = go.AddComponent<RunManager>();
            var database = ContentDatabase.Load();
            if (database == null)
                Debug.LogWarning(DeadManZoneEditorMenus.Content + "Generate Demo Content — content database missing.");

            var serialized = new SerializedObject(manager);
            serialized.FindProperty("contentDatabase").objectReferenceValue = database;
            serialized.ApplyModifiedPropertiesWithoutUndo();
            return manager;
        }

        /// <summary>Ensures MainMenu/Run are registered and enabled without dropping any other
        /// scene (e.g. CombatArena3D) a dev already added to Build Settings for their own
        /// testing — this used to hard-replace the whole list, which silently broke
        /// CombatArenaReplayPlayModeTests every time this menu item ran.</summary>
        private static void UpdateBuildSettings()
        {
            var others = EditorBuildSettings.scenes
                .Where(s => s.path != MainMenuPath && s.path != RunPath);

            var scenes = new[]
            {
                new EditorBuildSettingsScene(MainMenuPath, true),
                new EditorBuildSettingsScene(RunPath, true)
            }.Concat(others).ToArray();

            EditorBuildSettings.scenes = scenes;
        }

        internal static GameObject CreateStretchChild(Transform parent, string name)
        {
            var go = new GameObject(name, typeof(RectTransform));
            go.transform.SetParent(parent, false);
            var rect = go.GetComponent<RectTransform>();
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = Vector2.zero;
            rect.offsetMax = Vector2.zero;
            return go;
        }

        internal static TMP_Text CreateLabelPublic(
            Transform parent,
            string text,
            float fontSize,
            FontStyles style,
            Vector2 anchor,
            Vector2 size) =>
            CreateLabel(parent, text, fontSize, style, anchor, size);

        private static TMP_Text CreateLabel(
            Transform parent,
            string text,
            float fontSize,
            FontStyles style,
            Vector2? anchor = null,
            Vector2? size = null)
        {
            var go = new GameObject("Label", typeof(RectTransform));
            go.transform.SetParent(parent, false);
            var label = go.AddComponent<TextMeshProUGUI>();
            label.text = text;
            label.fontSize = fontSize;
            label.fontStyle = style;
            label.alignment = TextAlignmentOptions.Center;
            label.color = UiThemeProvider.Current.textPrimary;

            if (anchor.HasValue && size.HasValue)
                SetAnchored(label.rectTransform, anchor.Value, size.Value);

            return label;
        }

        internal static Button CreateButtonPublic(Transform parent, string label, Vector2 anchor) =>
            CreateButton(parent, label, anchor, new Vector2(320, 56));

        internal static Button CreateSmallButtonPublic(
            Transform parent,
            string label,
            Vector2 anchor,
            Vector2 size) =>
            CreateButton(parent, label, anchor, size);

        private static Button CreateButton(Transform parent, string label, Vector2 anchor)
        {
            return CreateButton(parent, label, anchor, new Vector2(320, 56));
        }

        private static Button CreateButton(Transform parent, string label, Vector2 anchor, Vector2 size)
        {
            var go = new GameObject(label + "Button", typeof(RectTransform));
            go.transform.SetParent(parent, false);
            var image = go.AddComponent<Image>();
            var theme = UiThemeProvider.Current;
            image.color = theme.buttonNormal;

            var button = go.AddComponent<Button>();
            UiThemeApplicator.ApplyButton(button, theme);

            SetAnchored(go.GetComponent<RectTransform>(), anchor, size);

            var textGo = new GameObject("Text", typeof(RectTransform));
            textGo.transform.SetParent(go.transform, false);
            var textRect = textGo.GetComponent<RectTransform>();
            textRect.anchorMin = Vector2.zero;
            textRect.anchorMax = Vector2.one;
            textRect.offsetMin = Vector2.zero;
            textRect.offsetMax = Vector2.zero;

            var tmp = textGo.AddComponent<TextMeshProUGUI>();
            tmp.text = label;
            tmp.fontSize = 26;
            tmp.alignment = TextAlignmentOptions.Center;
            tmp.color = Color.white;

            return button;
        }

        private static void SetAnchored(RectTransform rect, Vector2 anchor, Vector2 size)
        {
            rect.anchorMin = anchor;
            rect.anchorMax = anchor;
            rect.pivot = new Vector2(0.5f, 0.5f);
            rect.sizeDelta = size;
            rect.anchoredPosition = Vector2.zero;
        }

        private static void EnsureFolder(string path)
        {
            if (!AssetDatabase.IsValidFolder(path))
            {
                var parent = System.IO.Path.GetDirectoryName(path)?.Replace('\\', '/');
                var leaf = System.IO.Path.GetFileName(path);
                if (!string.IsNullOrEmpty(parent) && !AssetDatabase.IsValidFolder(parent))
                    EnsureFolder(parent);
                AssetDatabase.CreateFolder(parent, leaf);
            }
        }
    }
}
