using System.Collections.Generic;

namespace DeadManZone.Core.Tags
{
    /// <summary>User-authored tags generated by the Tag Creator editor.</summary>
    public static partial class CustomTagCatalog
    {
        public static IReadOnlyList<KeywordTagEntry> All => GeneratedEntries;
    }
}
