// <auto-generated by Tag Creator — do not edit manually>
using System.Collections.Generic;

namespace DeadManZone.Core.Tags
{
    public static partial class CustomTagCatalog
    {
        public static IReadOnlyList<KeywordTagEntry> GeneratedEntries { get; } = new KeywordTagEntry[]
        {
            new KeywordTagEntry
            {
                Id = "testsynergy",
                DisplayName = "Test Synergy",
                Category = TagCategory.Synergy,
                Tooltip = "test",
                DisplayPriority = 20
            }
        };
    }
}
