// <auto-generated by Tag Creator — do not edit manually>
using System.Collections.Generic;

namespace DeadManZone.Core.Tags
{
    public static partial class CustomTagCatalog
    {
        public static IReadOnlyList<KeywordTagEntry> GeneratedEntries { get; } = System.Array.Empty<KeywordTagEntry>();
    }
}
