using System.Collections.Generic;

namespace DeadManZone.Core.Combat
{
    public enum CombatAdvanceStatus
    {
        AwaitingCommand,
        Completed
    }

    public sealed class CombatAdvanceResult
    {
        public CombatAdvanceStatus Status { get; init; }
        /// <summary>Segment whose events were generated by this Continue call (for playback).</summary>
        public int SegmentIndex { get; init; }
        /// <summary>Set when Status is AwaitingCommand: why the pause fired.</summary>
        public PauseTriggerContext PauseTrigger { get; init; }
        public bool PlayerWon { get; init; }
        public bool IsDraw { get; init; }
        public BattleReport BattleReport { get; init; }
        public CombatEventLog EventLog { get; init; }
        public int PlayerCombatantsTotal { get; init; }
        public int PlayerCombatantsLost { get; init; }
        public bool PlayerHqDamaged { get; init; }
        public IReadOnlyList<string> SurvivingPlayerCombatantIds { get; init; } =
            System.Array.Empty<string>();
        public IReadOnlyList<CombatantState> PlayerCombatantsAtEnd { get; init; } =
            System.Array.Empty<CombatantState>();
    }
}
